### ISSUE TITLE
Reports tab cannot be selected.

### ISSUE THREAD

**Issue by mtkuntz** [Luxoft/Twister#102]
The Reports tab cannot be selected; if you are on the Configuration tab and mouse-click on Reports, it jumps to Projects.

twister (0.04). java build 7 update 45

Reports page opens from the Control Panel OK.

java.lang.NullPointerException
    at MainPanel$1.stateChanged(MainPanel.java:104)
    at javax.swing.JTabbedPane.fireStateChanged(Unknown Source)
    at javax.swing.JTabbedPane$ModelListener.stateChanged(Unknown Source)
    at javax.swing.DefaultSingleSelectionModel.fireStateChanged(Unknown Source)
    at javax.swing.DefaultSingleSelectionModel.setSelectedIndex(Unknown Source)
    at javax.swing.JTabbedPane.setSelectedIndexImpl(Unknown Source)
    at javax.swing.JTabbedPane.setSelectedIndex(Unknown Source)
    at javax.swing.plaf.basic.BasicTabbedPaneUI$Handler.mousePressed(Unknown Source)
    at java.awt.Component.processMouseEvent(Unknown Source)
    at javax.swing.JComponent.processMouseEvent(Unknown Source)
    at java.awt.Component.processEvent(Unknown Source)
    at java.awt.Container.processEvent(Unknown Source)
    at java.awt.Component.dispatchEventImpl(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
    at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
    at java.awt.Container.dispatchEventImpl(Unknown Source)
    at java.awt.Component.dispatchEvent(Unknown Source)
    at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
    at java.awt.EventQueue.access$200(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.awt.EventQueue$3.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue$4.run(Unknown Source)
    at java.awt.EventQueue$4.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by bogdanpopescu** [comment]
@mtkuntz 
Issue was fixed. Please verify.

**Comment by mtkuntz** [comment]
fixed in 043
