### ISSUE TITLE
java exceptions when running tests

### ISSUE THREAD

**Issue by mtkuntz** [Luxoft/Twister#114]
Java errors running test cases:
java.lang.NumberFormatException: For input string: "_ERROR for mkuntz!_ File `/home/mkuntz/twister/logs/pearl326_EP-1001_CLI.log` doesn't exist! Using master config `/home/mkuntz/twister/config/fwmconfig.xml` and suites config `/home/mkuntz/twister/config/testsuites.xml`"
    at java.lang.NumberFormatException.forInputString(Unknown Source)
    at java.lang.Long.parseLong(Unknown Source)
    at java.lang.Long.parseLong(Unknown Source)
    at Log.updateLog(Log.java:148)
    at Log$5.run(Log.java:133)
java.lang.NumberFormatException: For input string: "_ERROR for mkuntz!_ File `/home/mkuntz/twister/logs/pearl326_EP-1001_CLI.log` doesn't exist! Using master config `/home/mkuntz/twister/config/fwmconfig.xml` and suites config `/home/mkuntz/twister/config/testsuites.xml`"
    at java.lang.NumberFormatException.forInputString(Unknown Source)
    at java.lang.Long.parseLong(Unknown Source)
    at java.lang.Long.parseLong(Unknown Source)
    at Log.updateLog(Log.java:148)
    at Log$5.run(Log.java:133)

**Comment by bogdanpopescu** [comment]
@mtkuntz 
Fix delivered on 10th April. Please test.

**Comment by mtkuntz** [comment]
Have not seen these - Closing this issue.
