### ISSUE TITLE
smoke test crashed.

### ISSUE THREAD

**Issue by mtkuntz** [Luxoft/Twister#115]
TWISTER_PATH is set to `/home/mkuntz/twister`.

~ Start the Execution Process ~
~ User: mkuntz ; EP: pearl326_EP-1001 ; CE path: 127.0.0.1:8000 ~

EP Debug: Created a threaded logger.
EP Debug: Connecting to the Central Engine for the first time...
EP Debug: Connected and authenticated to CE at `127.0.0.1:8000`.

Downloading library `TscCommonLib.py` ...
... all libraries downloaded.

EP Debug: Start to run the tests!

===== ===== ===== ===== =====
 Starting suite `101 - Suite_01`
===== ===== ===== ===== =====

<<< START filename: `1001:/home/mkuntz/twister/demo/testsuite-python/test_py_printnlogs.py` >>>

TestCase:test_py_printnlogs.py starting

Test case exception:
File "/home/mkuntz/twister/client/executionprocess/ExecutionProcess.py", line 884, in tests
    result = current_runner._eval(str_to_execute, globs, args)
  File "/home/mkuntz/twister/client/executionprocess/RunnerClasses.py", line 249, in _eval
    execfile(fpath, globs_copy)
  File "/home/mkuntz/twister/.twister_cache/pearl326_EP-1001/test_py_printnlogs.py", line 38, in <module>
    _RESULT = test()
  File "/home/mkuntz/twister/.twister_cache/pearl326_EP-1001/test_py_printnlogs.py", line 21, in test
    logMsg('logDebug', "Py %s: working %i...\n" % (testName.upper(), i))
  File "/home/mkuntz/twister/.twister_cache/pearl326_EP-1001/ce_libs/TscCommonLib.py", line 167, in logMsg
    self.ce_proxy.logMessage(logType, logMessage)
  File "/usr/local/lib/python2.7/site-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/netref.py", line 196, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "/usr/local/lib/python2.7/site-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/netref.py", line 71, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/usr/local/lib/python2.7/site-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/protocol.py", line 435, in sync_request
    raise obj
EOFError: error(104, 'Connection reset by peer')

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/protocol.py", line 299, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/usr/local/lib/python2.7/site-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/protocol.py", line 529, in _handle_call
    return self._local_objects[oid](*args, **dict%28kwargs%29)
  File "/opt/twister/server/CeRpyc.py", line 1181, in exposed_logMessage
    return self.project.logMessage(user, logType, logMessage)
  File "/opt/twister/server/CeProject.py", line 3166, in logMessage
    return self.localFs.writeUserFile(user, logPath, logMessage, 'a')
  File "/opt/twister/server/CeFs.py", line 238, in writeUserFile
    return srvr.root.write_file(fpath, fdata, flag)
  File "/usr/local/lib/python2.7/site-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/netref.py", line 196, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "/usr/local/lib/python2.7/site-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/netref.py", line 71, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/usr/local/lib/python2.7/site-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/protocol.py", line 432, in sync_request
    self.serve(0.1)
  File "/usr/local/lib/python2.7/site-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/protocol.py", line 381, in serve
    data = self._recv(timeout, wait_for_lock = True)
  File "/usr/local/lib/python2.7/site-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/protocol.py", line 339, in _recv
    data = self._channel.recv()
  File "/usr/local/lib/python2.7/site-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/channel.py", line 50, in recv
    header = self.stream.read(self.FRAME_HEADER.size)
  File "/usr/local/lib/python2.7/site-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/stream.py", line 184, in read
    raise EOFError(ex)
EOFError: [Errno 104] Connection reset by peer

> > > File `/home/mkuntz/twister/demo/testsuite-python/test_py_printnlogs.py` execution CRASHED. <<<

Test statistics: Start time 2014-03-28 15:08:01 -- End time 2014-03-28 15:08:47 -- 45.54 sec.

<<< END filename: `1001:/home/mkuntz/twister/demo/testsuite-python/test_py_printnlogs.py` >>>
# 
# . . . All tests done . . .

**Comment by bogdanpopescu** [comment]
@mtkuntz 
Fix delivered on 10th April. Please test.

**Comment by mtkuntz** [comment]
Seems OK now
