### ISSUE TITLE
Unable to export test suite from the twister GUI

### ISSUE THREAD

**Issue by sandhyamisra** [Luxoft/Twister#121]
Build date 04-04-2014
When exporting the suite twister gives an error warning file not saved it doesnt get exported

![image](https://cloud.githubusercontent.com/assets/4291567/2631480/a67837b6-be59-11e3-989e-0260dc64a772.png)

**Comment by bogdanpopescu** [comment]
@sandhyamisra 
please check the configured path for exported suites in COnfiguration->Paths->Preedfined Suites Path.

**Comment by sandhyamisra** [comment]
The path is set to my home directory/Documents/Suites
Similar issue is seen for save project as option, Export project option

**Comment by bogdanpopescu** [comment]
@sandhyamisra 
Fix delivered on 10th April. Please test.

**Comment by sandhyamisra** [comment]
1.  File -> Save Project as option -> Works fine. Project gets saved in the projects path /home/smisra/twister/config/projects. However, I would expect when I ‘save project as’ the project which is open should be the newly named project (it works this way with any windows applications like MS word)
2.  File -> Export Project option -> This menu items says export project, however it is writing to the suite path: 
   Saving /home/smisra/Documents/Suite/ProjExport01.xml with CE
   writing: /home/smisra/Documents/Suite/ProjExport01.xml with CE 
   Doesn’t work as expected. 
3.  Suite -> Doesn’t have export suite option. The option is available in the short cut right click menu 
4.  Export Suite option Short cut (Right Click) menu -> Still doesn’t work! Same error as earlier (warning file not saved)
5.  Suite -> Contract and short cut (right click) menu option contract don’t work
6.  Suite ->  Set TB Option??
   java.lang.NullPointerException
       at Panel1.setEP(Panel1.java:1060)
       at Panel1.access$100(Panel1.java:83)
       at Panel1$6.actionPerformed(Panel1.java:160)
       at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
       at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
       at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
       at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
       at javax.swing.AbstractButton.doClick(Unknown Source)
       at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
       at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
       at java.awt.Component.processMouseEvent(Unknown Source)
       at javax.swing.JComponent.processMouseEvent(Unknown Source)
       at java.awt.Component.processEvent(Unknown Source)
       at java.awt.Container.processEvent(Unknown Source)
       at java.awt.Component.dispatchEventImpl(Unknown Source)
       at java.awt.Container.dispatchEventImpl(Unknown Source)
       at java.awt.Component.dispatchEvent(Unknown Source)
       at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
       at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
       at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
       at java.awt.Container.dispatchEventImpl(Unknown Source)
       at java.awt.Window.dispatchEventImpl(Unknown Source)
       at java.awt.Component.dispatchEvent(Unknown Source)
       at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
       at java.awt.EventQueue.access$200(Unknown Source)
       at java.awt.EventQueue$3.run(Unknown Source)
       at java.awt.EventQueue$3.run(Unknown Source)
       at java.security.AccessController.doPrivileged(Native Method)
       at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
       at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
       at java.awt.EventQueue$4.run(Unknown Source)
       at java.awt.EventQueue$4.run(Unknown Source)
       at java.security.AccessController.doPrivileged(Native Method)
       at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
       at java.awt.EventQueue.dispatchEvent(Unknown Source)
       at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
       at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
       at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
       at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
       at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
       at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by sandhyamisra** [comment]
Works fine on 11th April build
