### ISSUE TITLE
Unable to execute tests - CeRpycService error

### ISSUE THREAD

**Issue by leanderc** [Luxoft/Twister#139]
EP hangs indefinitly , Rpc error logs recieved in CE logger
Log below

~ Start the Execution Process ~
~ User: boskey ; EP: ubuntu_EP-boskey ; CE path: 127.0.0.1:8000 ~

Traceback (most recent call last):
  File "/home/boskey/twister/client/executionprocess/ExecutionProcess.py", line 1196, in <module>
    runner.main()
  File "/home/boskey/twister/client/executionprocess/ExecutionProcess.py", line 439, in main
    ce.setEpVariable(self.epName, 'twister_ep_os', system)
  File "/usr/local/lib/python2.7/dist-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/netref.py", line 150, in **getattr**
    return syncreq(self, consts.HANDLE_GETATTR, name)
  File "/usr/local/lib/python2.7/dist-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/netref.py", line 71, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/usr/local/lib/python2.7/dist-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/protocol.py", line 435, in sync_request
    raise obj
AttributeError: 'CeRpycService' object has no attribute 'exposed_setEpVariable'

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/protocol.py", line 299, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/usr/local/lib/python2.7/dist-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/protocol.py", line 535, in _handle_getattr
    return self._access_attr(oid, name, (), "_rpyc_getattr", "allow_getattr", getattr)
  File "/usr/local/lib/python2.7/dist-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/protocol.py", line 501, in _access_attr
    return accessor(obj, name, *args)
  File "/usr/local/lib/python2.7/dist-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/service.py", line 69, in _rpyc_getattr
    return getattr(self, name)
AttributeError: 'CeRpycService' object has no attribute 'exposed_setEpVariable'

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in **bootstrap_inner
    self.run()
  File "/home/boskey/twister/client/executionprocess/ExecutionProcess.py", line 308, in run
    self.logLive(data)
  File "/home/boskey/twister/client/executionprocess/ExecutionProcess.py", line 344, in logLive
    proxy().logLIVE(epName, binascii.b2a_base64(self.buffer))
  File "/usr/local/lib/python2.7/dist-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/netref.py", line 150, in __getattr**
    return syncreq(self, consts.HANDLE_GETATTR, name)
  File "/usr/local/lib/python2.7/dist-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/netref.py", line 71, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/usr/local/lib/python2.7/dist-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/protocol.py", line 435, in sync_request
    raise obj
AttributeError: 'CeRpycService' object has no attribute 'exposed_logLIVE'

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/protocol.py", line 299, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/usr/local/lib/python2.7/dist-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/protocol.py", line 535, in _handle_getattr
    return self._access_attr(oid, name, (), "_rpyc_getattr", "allow_getattr", getattr)
  File "/usr/local/lib/python2.7/dist-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/protocol.py", line 501, in _access_attr
    return accessor(obj, name, *args)
  File "/usr/local/lib/python2.7/dist-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/service.py", line 69, in _rpyc_getattr
    return getattr(self, name)
AttributeError: 'CeRpycService' object has no attribute 'exposed_logLIVE'

~ Stop the Execution Process ~

Exception on change status: `'CeRpycService' object has no attribute 'exposed_setEpStatus'

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/protocol.py", line 299, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/usr/local/lib/python2.7/dist-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/protocol.py", line 535, in _handle_getattr
    return self._access_attr(oid, name, (), "_rpyc_getattr", "allow_getattr", getattr)
  File "/usr/local/lib/python2.7/dist-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/protocol.py", line 501, in _access_attr
    return accessor(obj, name, *args)
  File "/usr/local/lib/python2.7/dist-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/service.py", line 69, in _rpyc_getattr
    return getattr(self, name)
AttributeError: 'CeRpycService' object has no attribute 'exposed_setEpStatus'
`!
Exception AttributeError: 'CeRpycService' object has no attribute 'exposed_logLIVE'

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/protocol.py", line 299, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/usr/local/lib/python2.7/dist-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/protocol.py", line 535, in _handle_getattr
    return self._access_attr(oid, name, (), "_rpyc_getattr", "allow_getattr", getattr)
  File "/usr/local/lib/python2.7/dist-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/protocol.py", line 501, in _access_attr
    return accessor(obj, name, *args)
  File "/usr/local/lib/python2.7/dist-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/service.py", line 69, in _rpyc_getattr
    return getattr(self, name)
AttributeError: 'CeRpycService' object has no attribute 'exposed_logLIVE'
 in <bound method TwisterRunner.__del__ of <**main**.TwisterRunner object at 0x7ff178e0da90>> ignored

**Comment by bogdanpopescu** [comment]
@leanderc 
You are using an old version of client in conjunction with a newer version of server. Please get the latest code changes, reinstall your client and restart the client.

**Comment by leanderc** [comment]
@bogdanpopescu 
Thanks for the reply . There wasnt any mention of the client code changes so left that the same.
ITs working now , how ever i am not able to access the getGlobal () methods in the test case
NameError: name 'getGlobal' is not defined
Have you guys made changes there too?

Test case exception below

Test case exception:
File "/home/boskey/twister/client/executionprocess/ExecutionProcess.py", line 1028, in tests
    result = current_runner._eval(str_to_execute, globs, args)
  File "/home/boskey/twister/client/executionprocess/RunnerClasses.py", line 266, in _eval
    execfile(fpath, globs_copy)
  File "/home/boskey/twister/.twister_cache/ubuntu_EP-Boskey/verify_catalog.py", line 6, in <module>
    jsonpath = getGlobal('postinfravalidate/jsonpath')
NameError: name 'getGlobal' is not defined

**Comment by leanderc** [comment]
@bogdanpopescu 

Hmm , the latest version , getGlobal is not get_global() ... This broke our code :(
Any particular reason for this change. Would you be continuing with get_global from now ?

**Comment by bogdanpopescu** [comment]
@leanderc 
We did the changes to improve pylint scoring. The user Guide is updated to reflect all this API changes.
Here is the list of API's:
- Log_msg( logType, message ) : this function sends a message in a special log and will not appear in the CLI. Valid log types are : logRunning, logDebug and logTest. It is used for sending debug messages from the tests.
- get_global( path ) : get a global parameter;
- set_global( path, new_value ) : set a global parameter;
- get_config( config_file_path, variable_path ) : get a config, using the full path to a config file and the full path to a config variable from that file.Very similar with getGlobal function;
- get_resource( ID or full path, [unicode | str] ) : get a resource;
- set_resource( ID or full path, new name ) : create, or update a resource;
- rename_resource( ID or full path, new name ) : rename one resource or property of a resource;
- delete_resource( ID or full path ) : delete one resource or property of a resource;
- get_sut( ID or full path, [unicode | str] ) : get a SUT properties;
- set_sut( ID or full path, new name ) : create, or update a SUT;
- delete_sut( ID or full path ) : delete one SUT or property of a SUT;
