### ISSUE TITLE
HTTP (REST) traceback error 

### ISSUE THREAD

**Issue by mmajdoubi** [Luxoft/Twister#164]
The REST interface (host:8000) crashes and generates an error if the user processes (users tab) are requested, the screenshots and the traceback error are listed below:

![screen shot 2015-01-15 at 14 36 45](https://cloud.githubusercontent.com/assets/846724/5758596/074b4c6c-9cc7-11e4-891d-81acd56a9253.png)

![screen shot 2015-01-15 at 14 36 54](https://cloud.githubusercontent.com/assets/846724/5758578/e65d5bda-9cc6-11e4-9d6f-91f4a2d2329c.png)

```
15-01-15 14:36:58  ERROR    [15/Jan/2015:14:36:58] HTTP Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.2-py2.7.egg/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.2-py2.7.egg/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/CherryPy-3.2.2-py2.7.egg/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/opt/twister/server/CeWebUi.py", line 170, in users
    eps_file=eps_file, eps=eps, ep_statuses=ep_statuses, logs=logs)
  File "/usr/local/lib/python2.7/dist-packages/Mako-0.9.1-py2.7.egg/mako/template.py", line 443, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/local/lib/python2.7/dist-packages/Mako-0.9.1-py2.7.egg/mako/runtime.py", line 807, in _render
    **_kwargs_for_callable(callable_, data))
  File "/usr/local/lib/python2.7/dist-packages/Mako-0.9.1-py2.7.egg/mako/runtime.py", line 839, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/local/lib/python2.7/dist-packages/Mako-0.9.1-py2.7.egg/mako/runtime.py", line 865, in _exec_template
    callable_(context, *args, **kwargs)
  File "_opt_twister_server_template_rest_user_htm", line 73, in render_body
KeyError: 'suites'
```

Thanks in advance

**Comment by bogdanpopescu** [comment]
The REST interface is experimental and we do not provide support for it.

**Comment by mmajdoubi** [comment]
Ok, Thanks.
I though that this error could be relevant and it may impact other
functionalities. If this error is not relevant the case can be closed.

Op donderdag 15 januari 2015 heeft Bogdan Popescu notifications@github.com
het volgende geschreven:
