### ISSUE TITLE
Stop button not responding or not stopping the execution

### ISSUE THREAD

**Issue by Hamza989** [Luxoft/Twister#182]
We are unable to stop the test by pressing the "stop" button.  
This issue exist for all the twister user. 
![ded56eae-849f-11e5-92bc-83963f00042d](https://cloud.githubusercontent.com/assets/11990069/11085455/93c9ac7e-886c-11e5-9ddf-74b18ec24c04.png)

Since we are using twister continuously for executing tests, we cannot restart the central engine for resolving this issue.
Kindly suggest how can we fix this

**Comment by Hamza989** [comment]
This issue Persist with V 3.057. We are still facing the issue ,ie Stop button not responding for all the users of Twister.

**Comment by Hamza989** [comment]
Hi team,
As  this is blocking our automation testing, or we would like to request you to consider this in high priority ..
Can you please provide any work around to kill the execution and the restart with particular user without restarting central engine.
We have tried to kill the background process ,but it resulted in run button disabled state

**Comment by bogdanpopescu** [comment]
@Hamza989 
Hi, we are trying to reproduce this issue without success. In the meantime, I think the workaround would be to stop the execution ( clear it's state ) using cli.py utility in a terminal. 
Go to ~/twister/bin and issue the command:
python cli.py  --server=<ip+address>:8000 --login=<your_user>:<password> -s stop

**Comment by Hamza989** [comment]
HI,

We have tried following command to stop the execution, It has given me an exception as follows..

 

 

$ python cli.py --server 127.0.0.1:8000 --login user11:passwd -s stop

 

Hello, user `user11`.

Authentication successful!

 

Stopping...

Traceback (most recent call last):

  File "cli.py", line 508, in <module>

    print PROXY.set_ep_status_all(0, OPTIONS.config + ',' + OPTIONS.project)

  File "/usr/lib/python2.7/site-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/netref.py", line 196, in **call**

    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)

  File "/usr/lib/python2.7/site-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/netref.py", line 71, in syncreq

    return conn.sync_request(handler, oid, *args)

  File "/usr/lib/python2.7/site-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/protocol.py", line 441, in sync_request

    raise obj

KeyError: 'user11'

 

========= Remote Traceback (1) =========

Traceback (most recent call last):

  File "/usr/lib/python2.7/site-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/protocol.py", line 305, in _dispatch_request

    res = self._HANDLERS[handler](self, *args)

  File "/usr/lib/python2.7/site-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/protocol.py", line 535, in _handle_call

    return self._local_objects[oid](*args, **dict%28kwargs%29)

  File "/opt/twister/server/CeRpyc.py", line 1030, in exposed_set_ep_status_all

    return self.project.set_exec_status(user, epname, new_status, msg)

  File "/opt/twister/server/CeProject.py", line 2064, in set_exec_status_all

    reserved_suts_ids = reserved_suts[user].keys()

KeyError: 'user11'

 

-Hamza

**Comment by bogdanpopescu** [comment]
@Hamza989 
You HAVE to use equal sign for server and login:
python cli.py --server=your_server:8000 --login=your_user:your_password -s stop

**Comment by Hamza989** [comment]
We are still getting the exception with ‘=’  also

 

 

 

 

 

$ python cli.py --server=127.0.0.1:8000 --login=user11:passwd --stats

 

Hello, user `user11`.

Authentication successful!

 

User status : running

Last started: 2015-11-19 01:19:02

Time elapsed: 0:00:47

 

Passed  : 0

Failed  : 0

Pending : 0

Working : 1

Aborted : 0

No Exec : 0

Other   : 0

> Total : 1

Pass rate: 0.0%

 

$

$

$ python cli.py --server=127.0.0.1:8000 --login=user11:passwd -s stop

 

Hello, user `user11`.

Authentication successful!

 

Stopping...

Traceback (most recent call last):

  File "cli.py", line 508, in <module>

    print PROXY.set_ep_status_all(0, OPTIONS.config + ',' + OPTIONS.project)

  File "/usr/lib/python2.7/site-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/netref.py", line 196, in __call__

    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)

  File "/usr/lib/python2.7/site-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/netref.py", line 71, in syncreq

    return conn.sync_request(handler, oid, *args)

  File "/usr/lib/python2.7/site-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/protocol.py", line 441, in sync_request

    raise obj

KeyError: 'user11'

 

========= Remote Traceback (1) =========

Traceback (most recent call last):

  File "/usr/lib/python2.7/site-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/protocol.py", line 305, in _dispatch_request

    res = self._HANDLERS[handler](self, *args)

  File "/usr/lib/python2.7/site-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/protocol.py", line 535, in _handle_call

    return self._local_objects[oid](*args, **dict(kwargs))

  File "/opt/twister/server/CeRpyc.py", line 1030, in exposed_set_ep_status_all

    return self.project.set_exec_status(user, epname, new_status, msg)

  File "/opt/twister/server/CeProject.py", line 2064, in set_exec_status_all

    reserved_suts_ids = reserved_suts[user].keys()

KeyError: 'user11'

 

$

**Comment by Hamza989** [comment]
We are getting the exception while executing this command

$ python cli.py --server=127.0.0.1:8000 --login=user11:passwd --stats

Hello, user `user11`.
Authentication successful!

User status : running
Last started: 2015-11-19 01:19:02
Time elapsed: 0:00:47

Passed  : 0
Failed  : 0
Pending : 0
Working : 1
Aborted : 0
No Exec : 0
Other   : 0

> Total : 1
> Pass rate: 0.0%

$
$
$ python cli.py --server=127.0.0.1:8000 --login=user11:passwd -s stop

Hello, user `user11`.
Authentication successful!

Stopping...
Traceback (most recent call last):
  File "cli.py", line 508, in <module>
    print PROXY.set_ep_status_all(0, OPTIONS.config + ',' + OPTIONS.project)
  File "/usr/lib/python2.7/site-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/netref.py", line 196, in **call**
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "/usr/lib/python2.7/site-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/netref.py", line 71, in syncreq
    return conn.sync_request(handler, oid, *args)
  File "/usr/lib/python2.7/site-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/protocol.py", line 441, in sync_request
    raise obj
KeyError: 'user11'

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/protocol.py", line 305, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "/usr/lib/python2.7/site-packages/rpyc-3.3.0-py2.7.egg/rpyc/core/protocol.py", line 535, in _handle_call
    return self._local_objects[oid](*args, **dict%28kwargs%29)
  File "/opt/twister/server/CeRpyc.py", line 1030, in exposed_set_ep_status_all
    return self.project.set_exec_status(user, epname, new_status, msg)
  File "/opt/twister/server/CeProject.py", line 2064, in set_exec_status_all
    reserved_suts_ids = reserved_suts[user].keys()
KeyError: 'user11'

$

**Comment by bogdanpopescu** [comment]
@Hamza989 
Does your test case lauch threads ?

**Comment by Hamza989** [comment]
Stops button not responding even before starting the threads..

**Comment by bogdanpopescu** [comment]
@Hamza989 
Did you used kill -9 command against start_clinet.py ?

**Comment by Hamza989** [comment]
No,  We have not used that command to kill this particular user.

**Comment by bogdanpopescu** [comment]
@Hamza989 
I guess you are not using the latest Twister version ( 3.066, Build date 06.11.2015 ). This version has code to restore/reset the status when client is restarted and it should fix your issue.
Please upgrade and test it.

**Comment by Hamza989** [comment]
Yes, You are right, We are using version v.:3.057, going to upgrade to 3.066 and verify it.

**Comment by Hamza989** [comment]
Verified with v.3.067 version of twister , Stop button is working for all users
It might be because user has forcefully must have killed background process by using kill -9 command, which might be caused Stop Button not working. .

**Comment by Hamza989** [comment]
We are seeing that stop button not responding , this issue is found on v.3.068.
Execution server log shows following error : 
180345 17-07-14 13:48:06  ERROR    [14/Jul/2017:13:48:06] HTTP
180346 Traceback (most recent call last):
180347   File "/usr/lib/python2.7/site-packages/CherryPy-8.7.0-py2.7.egg/cherrypy/_cprequest.py", line 670, in respond
180348     response.body = self.handler()
180349   File "/usr/lib/python2.7/site-packages/CherryPy-8.7.0-py2.7.egg/cherrypy/lib/encoding.py", line 220, in __call__
180350     self.body = self.oldhandler(*args, **kwargs)
180351   File "/usr/lib/python2.7/site-packages/CherryPy-8.7.0-py2.7.egg/cherrypy/_cpdispatch.py", line 60, in __call__
180352     return self.callable(*self.args, **self.kwargs)
180353   File "/opt/twister/server/CeXmlRpc.py", line 93, in default
180354     resp = super(CeXmlRpc, self).default(*vpath, **params)
180355   File "/usr/lib/python2.7/site-packages/CherryPy-8.7.0-py2.7.egg/cherrypy/_cptools.py", line 378, in default
180356     body = subhandler(*(vpath + rpcparams), **params)
180357   File "/opt/twister/server/CeXmlRpc.py", line 1418, in set_exec_status_all
180358     return self.project.set_exec_status_all(user, new_status, msg)
180359   File "/opt/twister/server/CeProject.py", line 2140, in set_exec_status_all
180360     reserved_suts_ids = reserved_suts[user].keys()
180361 KeyError: 'TEST_USER110'
