### ISSUE TITLE
Start/Stop/Pause a script/suite through CLI doesn't work

### ISSUE THREAD

**Issue by sandhyamisra** [Luxoft/Twister#24]
Unable to execute a testsuite through CLI. 

Below is the command we have issued below followed by the error message.  (The syntax is as per the Twister-Guide)

user@user-VirtualBox:~/twister/bin$ python cli.py -s start -p ~/twister/config/users/MYTEST.XML -c ~/twister/config/fwmconfig.xml

Hello, user `user`.

Starting...
Traceback (most recent call last):
  File "cli.py", line 314, in <module>
    print proxy.setExecStatusAll(user, 2, options.config + ',' + options.project)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in **call**
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
   verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1297, in single_request
    return self.parse_response(response)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1473, in parse_response
    return u.close()
  File "/usr/lib/python2.7/xmlrpclib.py", line 793, in close
    raise Fault(**self._stack[0])
xmlrpclib.Fault: <Fault 1: 'list index out of range'>

**Comment by bogdanpopescu** [comment]
Please make sure you are using cli.py version 2.003. It was updated today.

**Comment by sandhyamisra** [comment]
Verified for 2.0003 as well... this still doesn't work

**Comment by bogdanpopescu** [comment]
Ok, is the project file built with the new version of applet ? The file must contain a tag called EpId.

**Comment by sandhyamisra** [comment]
This issue can be closed. Able to run scripts through CLI
