### ISSUE TITLE
cli.py fails on V:2.018

### ISSUE THREAD

**Issue by mtkuntz** [Luxoft/Twister#63]
aside from --help nothing works.

Traceback (most recent call last):
  File "cli.py", line 266, in <module>
    if os.path.isdir(userHome(user) + os.sep + 'twister'):
  File "cli.py", line 67, in userHome
    return subprocess.check_output('echo ~' + user, shell=True).strip()
AttributeError: 'module' object has no attribute 'check_output'

**Comment by mtkuntz** [comment]
operator error.
I was not defaulted to python 2.7
changed first line of cli.py to
#!/usr/bin/env python2.7

one way of fixing this.

**Comment by mtkuntz** [comment]
still not working - does not seem to use my uid:pid

Cannot connect to Central Engine server! Error `<ProtocolError for user:password@127.0.0.1:8000/: 401 Unauthorized>` ! Exiting!

**Comment by mtkuntz** [comment]
OK to Close
